{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: {{ .project | default "default" }}
  source:
    repoURL: {{ $.Values.config.repoURL }}
    targetRevision: {{ .targetRevision | default $.Values.config.targetRevision }}
    path: {{ .path }}
    {{- with .helm }}
    helm:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  destination:
    {{- toYaml .destination | nindent 4 }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    {{- with .syncOptions }}
    syncOptions:
      {{- toYaml . | nindent 6 }}
    {{- end }}
---
{{- end }}
